spring.application.name=Reservas-Parking
server.port=8081

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Importante: Permite conexiones externas a la consola si algo lo bloquea
spring.h2.console.settings.web-allow-others=true

# Database Connection
spring.datasource.url=jdbc:h2:mem:parkingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true